"""add Sub

Revision ID: 86e3fc414863
Revises: ed880b92ff8d
Create Date: 2025-02-19 19:44:40.526229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86e3fc414863"
down_revision: Union[str, None] = "ed880b92ff8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frequencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_frequencies_title"), "frequencies", ["title"], unique=True)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "start_date", sa.Date(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("frequency_id", sa.Integer(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["frequency_id"],
            ["frequencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_payment_date"),
        "subscriptions",
        ["payment_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_start_date"),
        "subscriptions",
        ["start_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_title"), "subscriptions", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_title"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_start_date"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_payment_date"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_frequencies_title"), table_name="frequencies")
    op.drop_table("frequencies")
    # ### end Alembic commands ###
